In [1]:
import numpy as np
import node
from node import MakeGoal

In [14]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):

# test 3 puzzle with UCS
a = np.array([[1,2],
              [3,0]])

goalA = MakeGoal(3)

rootA = node.Node(a, None, 0, 0, 0)
print(rootA.GeneralSearch(rootA.UniformCost, goalA))


[[1 2]
 [3 0]]
[[1 2]
 [3 0]]
[[1 2]
 [3 0]]


In [15]:
# Test 8 puzzle wtih UCS
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,0]])

goalB = MakeGoal(8)
rootB = node.Node(b, None, 0, 0, 0)
print(rootB.GeneralSearch(rootB.UniformCost, goalB))

[[1 2 3]
 [4 5 6]
 [7 8 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [16]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):
# test misplaced tile heuristic
a = np.array([[1,0],
              [3,2]])

goalA = MakeGoal(3)
hc = np.sum(a == goalA) 
print(hc)

rootA = node.Node(a, None, 0, 0, hc)
print(rootA.GeneralSearch(rootA.UniformCost, goalA))

2
