In [1]:
import numpy as np
import node
from node import MakeGoal

In [ ]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):

# test 3 puzzle with UCS
a = np.array([[1,2],
              [3,0]])

goalA = MakeGoal(3)

rootA = node.Node(a, None, 0, 0, 0)
print(rootA.GeneralSearch(rootA.UniformCost, goalA))


In [ ]:
# Test 8 puzzle wtih UCS
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,0]])

goalB = MakeGoal(8)
rootB = node.Node(b, None, 0, 0, 0)
print(rootB.GeneralSearch(rootB.UniformCost, goalB))

In [2]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):
# test misplaced tile heuristic with 3 puzzle
a = np.array([[1,0],
              [3,2]])

goalA = MakeGoal(3)
hc = np.sum(a != goalA) 

rootA = node.Node(a, None, 0, 0, hc)
print(rootA.GeneralSearch(rootA.MisplacedTile, goalA))

Heuristic Cost: 2, Depth: 0 
 [[1 0]
 [3 2]] 

Heuristic Cost: 0, Depth: 1 
 [[1 2]
 [3 0]] 

[[1 2]
 [3 0]]


In [ ]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):
# test misplaced tile heuristic with 8 puzzle
b = np.array([[1,2,3],
              [4,8,0],
              [7,6,5]])

goalB = MakeGoal(8)
hc = np.sum(b != goalB)
rootB = node.Node(b, None, 0, 0, hc)
print(rootB.GeneralSearch(rootB.MisplacedTile, goalB))