In [1]:
import numpy as np
import node
from node import MakeGoal
from math import sqrt
import time

In [ ]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):

# test 3 puzzle with UCS
a = np.array([[1,2],
              [3,0]])

goalA = MakeGoal(3)

rootA = node.Node(a, None, 0, 0, 0)
print(rootA.GeneralSearch(rootA.UniformCost, goalA))


In [ ]:
# Test 8 puzzle wtih UCS
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,0]])

goalB = MakeGoal(8)
rootB = node.Node(b, None, 0, 0, 0)
print(rootB.GeneralSearch(rootB.UniformCost, goalB))

In [ ]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):
# test misplaced tile heuristic with 3 puzzle
a = np.array([[1,0],
              [3,2]])

goalA = MakeGoal(3)
hc = np.sum(a != goalA) 

rootA = node.Node(a, None, 0, 0, hc)
print(rootA.GeneralSearch(rootA.MisplacedTile, goalA))

In [ ]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):
# test misplaced tile heuristic with 8 puzzle
b = np.array([[1,2,3],
              [4,8,0],
              [7,6,5]])

goalB = MakeGoal(8)
hc = np.sum(b != goalB)
rootB = node.Node(b, None, 0, 0, hc)
print(rootB.GeneralSearch(rootB.MisplacedTile, goalB))

In [ ]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):
# test manhattan heuristic with 3 puzzle
a = np.array([[1,0],
              [3,2]])

goalA = MakeGoal(3)

rootA = node.Node(a, None, 0, 0, 0)
print(rootA.GeneralSearch(rootA.Manhattan, goalA))

In [ ]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):
# test manhattan heuristic with 8 puzzle
b = np.array([[4,1,2],
              [5,3,0],
              [7,8,6]])

goalB = MakeGoal(8)

rootB = node.Node(b, None, 0, 0, 0)
print(rootB.GeneralSearch(rootB.Manhattan, goalB))

In [ ]:
# def __init__(self, BoardState, Parent, Depth, PathCost, HeuristicCost):
# test manhattan heuristic with a (harder) 8 puzzle
b = np.array([[1,5,2],
              [4,8,0],
              [6,3,7]])

goalB = MakeGoal(8)

rootB = node.Node(b, None, 0, 0, 0)
print(rootB.GeneralSearch(rootB.Manhattan, goalB))

In [2]:
# user constructed puzzle
while True:
    try:
        value = int(input("Choose one of the following:\n [1] Uniform Cost Search\n [2] A* with misplaced tile heuristic\n [3] A* with manhattan heuristic"))
    except ValueError:
        print("Enter a number within the range 1-3")
        continue
    if value in range(1,5):
        break
    else:
        print("Enter a number within the range 1-3")

while True:
    try:
        sz = int(input("What size puzzle would you like to run?: "))
        goal = MakeGoal(sz)
    except ValueError:
        print("Try a different number")
        continue
    if isinstance(goal, str):
        print("Try a different number")
    else:
        break

print("Enter your initial state array (one element at a time):\n")
size = int(sqrt(sz + 1))
arr = np.empty([size, size], dtype=int)
for i in range(size):
    for j in range(size):
        arr[i,j] = int(input(f"Element at: ({i},{j})"))

print(f"Your array:\n {arr}\n Goal array:\n {goal}\n")

if(value == 1):
    # uniform cost
    root = node.Node(arr, None, 0, 0, 0) 
    startTime = time.time()
    root.GeneralSearch(root.UniformCost, goal)
    print("Uniform Cost Search: %s seconds" % (time.time() - startTime))
elif(value == 2):
    # misplaced tile 
    hc = np.sum(arr != goal) # heuristic cost
    root = node.Node(arr, None, 0, 0, hc) 
    startTime = time.time()
    root.GeneralSearch(root.MisplacedTile, goal)
    print("Misplaced Tile: %s seconds" % (time.time() - startTime))
elif(value == 3):
    # manhattan distance
    root = node.Node(arr, None, 0, 0, 0) 
    startTime = time.time()
    root.GeneralSearch(root.Manhattan, goal)
    print("Manhattan: %s seconds" % (time.time() - startTime))
elif(value == 4):
    # This state is for testing purposes only
    hc = np.sum(arr != goal) # heuristic cost
    # uniform cost
    root = node.Node(arr, None, 0, 0, 0) 
    startTime = time.time()
    root.GeneralSearch(root.UniformCost, goal)
    print("Uniform Cost: %s seconds" % (time.time() - startTime))
    # misplaced
    root = node.Node(arr, None, 0, 0, hc) 
    startTime = time.time()
    root.GeneralSearch(root.MisplacedTile, goal)
    print("Misplaced: %s seconds" % (time.time() - startTime))
    # Manhattan 
    root = node.Node(arr, None, 0, 0, 0) 
    startTime = time.time()
    root.GeneralSearch(root.Manhattan, goal)
    print("Manhattan: %s seconds" % (time.time() - startTime))


Enter your initial state array (one element at a time):

Your array:
 [[7 1 2]
 [4 8 5]
 [6 3 0]]
 Goal array:
 [[1 2 3]
 [4 5 6]
 [7 8 0]]

Best Node: h(n): 0, g(n): 0 
 [[7 1 2]
 [4 8 5]
 [6 3 0]] 

Best Node: h(n): 14, g(n): 15 
 [[7 1 2]
 [4 8 0]
 [6 3 5]] 

Best Node: h(n): 12, g(n): 13 
 [[7 1 2]
 [4 8 5]
 [6 0 3]] 

Best Node: h(n): 12, g(n): 14 
 [[7 1 2]
 [4 0 5]
 [6 8 3]] 

Best Node: h(n): 12, g(n): 14 
 [[7 1 2]
 [4 8 5]
 [0 6 3]] 

Best Node: h(n): 14, g(n): 17 
 [[7 1 2]
 [0 8 5]
 [4 6 3]] 

Best Node: h(n): 10, g(n): 13 
 [[7 1 2]
 [4 5 0]
 [6 8 3]] 

Best Node: h(n): 12, g(n): 16 
 [[7 1 0]
 [4 5 2]
 [6 8 3]] 

Best Node: h(n): 8, g(n): 12 
 [[7 1 2]
 [4 5 3]
 [6 8 0]] 

Best Node: h(n): 10, g(n): 15 
 [[7 1 2]
 [4 5 3]
 [6 0 8]] 

Best Node: h(n): 14, g(n): 17 
 [[7 0 2]
 [4 1 5]
 [6 8 3]] 

Best Node: h(n): 14, g(n): 17 
 [[7 1 2]
 [0 4 5]
 [6 8 3]] 

Best Node: h(n): 12, g(n): 18 
 [[7 1 2]
 [4 0 3]
 [6 5 8]] 

Best Node: h(n): 10, g(n): 16 
 [[7 1 2]
 [4 5 3]
 [0 6 